site_name: KICL Documentation
repo_url: https://github.com/KittehOrg/KittehIRCClientLib
pages:
- Home: index.md
- Events: events.md
- IRCv3 Support: ircv3.md
- Common Problems: common_problems.md
- Advanced:
  - Account Tracking: advanced/accounts.md
  - SSL: advanced/ssl.md
  - SSL root import: advanced/ssl_import.md
  - STS: advanced/sts.md
  - WEBIRC: advanced/webirc.md
  - SASL: advanced/sasl.md
  - ECDSA: advanced/ecdsa.md
  - Alternative Authentication: advanced/alt_auth.md
markdown_extensions: [fenced_code]
theme: readthedocs
