site_name: KICL Documentation
repo_url: https://github.com/KittehOrg/KittehIRCClientLib
pages:
- Home: index.md
- Events: events.md
- IRCv3 Support: ircv3.md
- Advanced:
  - Account Tracking: advanced/accounts.md
  - SSL: advanced/ssl.md
  - WEBIRC: advanced/webirc.md

markdown_extensions: [fenced_code]
theme: readthedocs